schemaVersion: 2.1.0
metadata:
  name: developer-images
attributes:
  controller.devfile.io/storage-type: ephemeral
  controller.devfile.io/scc: container-build
components:
  - name: devtools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryLimit: 2Gi
      memoryRequest: 256Mi
      volumeMounts:
        - name: containers
          path: /home/user/.local/share/containers
  - name: containers
    volume:
      ephemeral: true
      size: 5Gi
