[storage]

# Default Storage Driver, Must be set for proper operation.
driver = "overlay"

# Temporary storage location
runroot = "/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

# Storage path for rootless users
rootless_storage_path = "/var/lib/containers/users/$USER"

[storage.options]

additionalimagestores = [
  "var/lib/shared",
]

pull_options = {enable_partial_images = "false", use_hard_links = "false", ostree_repos="" }

[storage.options.overlay]
ignore_chown_errors = "true"

mount_program = "/usr/bin/fuse-overlayfs"

mount_opt = "nodev,metacopy=on"
